# Generated by Django 4.0.4 on 2022-04-12 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n', models.IntegerField()),
                ('t', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nfa_nfa', models.TextField()),
                ('nfa_pandas', models.TextField()),
                ('dfa_dfa', models.TextField()),
                ('dfa_pandas', models.TextField()),
            ],
        ),
    ]
