# Generated by Django 4.0.4 on 2022-06-15 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='counter',
            name='recahng',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
