# Generated by Django 4.0.4 on 2022-06-15 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_counter_recahng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counter',
            name='recahng',
            field=models.IntegerField(default=None),
        ),
    ]
